from __future__ import annotations

import json
import sys
from datetime import UTC, datetime
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from Monitoring.build_mongodb_exporter_all_metrics_dashboard import PROM_DS, row_panel, stat_panel, target, timeseries_panel

OUTPUT = Path("Monitoring/mongodb_exporter_core_metrics_dashboard.json")
PROGRESS = Path("Monitoring/mongodb_exporter_core_metrics_progress.json")
RATE_INTERVAL = "$__rate_interval"


def add_row(panels: list[dict], panel_id: int, y: int, title: str, specs: list[dict]) -> tuple[int, int, list[dict]]:
    panels.append(row_panel(panel_id, title, y))
    panel_id += 1
    y += 1
    x = 0
    records: list[dict] = []
    for spec in specs:
        width = spec.get("width", 8)
        height = spec.get("height", 8)
        if x + width > 24:
            x = 0
            y += height
        panels.append(timeseries_panel(panel_id, spec["title"], spec["description"], spec["targets"], x, y, spec.get("unit", "none"), width=width, height=height))
        records.append({"title": spec["title"], "unit": spec.get("unit", "none"), "metrics": spec.get("metrics", []), "description": spec["description"]})
        panel_id += 1
        x += width
    y += (specs[-1].get("height", 8) if specs else 0) + 1
    return panel_id, y, records


def overview(panel_id: int, y: int) -> tuple[list[dict], int, int, dict]:
    panels = [row_panel(panel_id, "Overview", y)]
    panel_id += 1
    y += 1
    stats = [
        ("MongoDB Up", 'max(mongodb_up{instance="$instance"})', "Shows whether the selected MongoDB target is scrapeable from Prometheus.", "none", ["mongodb_up"]),
        ("Uptime", 'max(mongodb_ss_uptime{instance="$instance"})', "Server uptime in seconds since the mongod process started.", "s", ["mongodb_ss_uptime"]),
        ("Current Connections", 'max(mongodb_ss_connections{instance="$instance",conn_type="current"})', "Current client connections accepted by MongoDB.", "short", ["mongodb_ss_connections{conn_type=\"current\"}"]),
        ("Connections Used %", '100 * max(mongodb_ss_connections{instance="$instance",conn_type="current"}) / clamp_min(max(mongodb_ss_connections{instance="$instance",conn_type="current"}) + max(mongodb_ss_connections{instance="$instance",conn_type="available"}), 1)', "Approximate connection pool utilization derived from current and available connection slots.", "percent", ["mongodb_ss_connections{conn_type=\"current\"}", "mongodb_ss_connections{conn_type=\"available\"}"]),
        ("WT Cache Used %", '100 * max(mongodb_ss_wt_cache_bytes_currently_in_the_cache{instance="$instance"}) / clamp_min(max(mongodb_ss_wt_cache_maximum_bytes_configured{instance="$instance"}), 1)', "Percent of WiredTiger cache currently in use. Sustained high values can precede eviction pressure and stalls.", "percent", ["mongodb_ss_wt_cache_bytes_currently_in_the_cache", "mongodb_ss_wt_cache_maximum_bytes_configured"]),
        ("Max Scrape Time", 'max(collector_scrape_time_ms{instance="$instance"})', "Maximum exporter collector scrape time in milliseconds. Useful to spot exporter overhead or stalled collectors.", "ms", ["collector_scrape_time_ms"]),
    ]
    records = {"title": "Overview", "stat_panels": [], "timeseries_panels": []}
    for index, (title, expr, description, unit, metrics) in enumerate(stats):
        panels.append(stat_panel(panel_id + index, title, description, expr, index * 4, y, unit))
        records["stat_panels"].append({"title": title, "unit": unit, "metrics": metrics, "description": description})
    panel_id += len(stats)
    y += 4
    overview_specs = [
        {"title": "Opcounters - Ops/sec", "description": "Per-second MongoDB operation rate split by legacy operation type. Useful for seeing whether load is read-heavy, write-heavy, or command-heavy.", "targets": [target('sum by (legacy_op_type) (rate(mongodb_ss_opcounters{instance="$instance"}[$__rate_interval]))', 0, "{{legacy_op_type}}")], "unit": "ops", "metrics": ["mongodb_ss_opcounters"]},
        {"title": "Average Operation Latency - ms", "description": "Average command, read, write, and transaction latency derived from cumulative opLatencies counters.", "targets": [target('rate(mongodb_ss_opLatencies_latency{instance="$instance",op_type="commands"}[$__rate_interval]) / clamp_min(rate(mongodb_ss_opLatencies_ops{instance="$instance",op_type="commands"}[$__rate_interval]), 1) / 1000', 0, "commands"), target('rate(mongodb_ss_opLatencies_latency{instance="$instance",op_type="reads"}[$__rate_interval]) / clamp_min(rate(mongodb_ss_opLatencies_ops{instance="$instance",op_type="reads"}[$__rate_interval]), 1) / 1000', 1, "reads"), target('rate(mongodb_ss_opLatencies_latency{instance="$instance",op_type="writes"}[$__rate_interval]) / clamp_min(rate(mongodb_ss_opLatencies_ops{instance="$instance",op_type="writes"}[$__rate_interval]), 1) / 1000', 2, "writes"), target('rate(mongodb_ss_opLatencies_latency{instance="$instance",op_type="transactions"}[$__rate_interval]) / clamp_min(rate(mongodb_ss_opLatencies_ops{instance="$instance",op_type="transactions"}[$__rate_interval]), 1) / 1000', 3, "transactions")], "unit": "ms", "metrics": ["mongodb_ss_opLatencies_latency", "mongodb_ss_opLatencies_ops"]},
        {"title": "Slow Query Rate - Queries/sec", "description": "Per-second slow query rate by database using profiler-derived counters. Spikes here often accompany user-visible slowness.", "targets": [target('sum by (database) (rate(mongodb_profile_slow_query_count{instance="$instance"}[$__rate_interval]))', 0, "{{database}}")], "unit": "ops", "metrics": ["mongodb_profile_slow_query_count"]},
    ]
    for index, spec in enumerate(overview_specs):
        panels.append(timeseries_panel(panel_id + index, spec["title"], spec["description"], spec["targets"], index * 8, y, spec["unit"]))
        records["timeseries_panels"].append({"title": spec["title"], "unit": spec["unit"], "metrics": spec["metrics"], "description": spec["description"]})
    return panels, panel_id + len(overview_specs), y + 9, records


def build_dashboard() -> tuple[dict, dict]:
    panels, panel_id, y, overview_record = overview(1, 0)
    row_records = [overview_record]
    rows = [
        ("Connections & Network", [
            {"title": "Connections - Current Values", "description": "Current connection counters and queue gauges. Rising current or queued connections can indicate saturation or slow clients.", "targets": [target('mongodb_ss_connections{instance="$instance",conn_type=~"active|available|current|queuedForEstablishment|rejected"}', 0, "{{conn_type}}")], "unit": "short", "metrics": ["mongodb_ss_connections"]},
            {"title": "Connections Created - Count/sec", "description": "Rate of newly created connections. Spikes can point to connection churn, missing pooling, or client reconnect storms.", "targets": [target(f'rate(mongodb_ss_connections{{instance="$instance",conn_type="totalCreated"}}[{RATE_INTERVAL}])', 0, "created/sec")], "unit": "ops", "metrics": ["mongodb_ss_connections{conn_type=\"totalCreated\"}"]},
            {"title": "Network Throughput - Bytes/sec", "description": "Logical and physical network throughput into and out of MongoDB. Useful for separating client traffic from wire-level compression effects.", "targets": [target(f'rate(mongodb_ss_network_bytesIn{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "bytes in"), target(f'rate(mongodb_ss_network_bytesOut{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "bytes out"), target(f'rate(mongodb_ss_network_physicalBytesIn{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "physical in"), target(f'rate(mongodb_ss_network_physicalBytesOut{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "physical out")], "unit": "Bps", "metrics": ["mongodb_ss_network_bytesIn", "mongodb_ss_network_bytesOut", "mongodb_ss_network_physicalBytesIn", "mongodb_ss_network_physicalBytesOut"]},
            {"title": "Requests & Admission Control - Count/sec", "description": "Per-second request volume plus ingress admission attempts, successes, exemptions, and rejects.", "targets": [target(f'rate(mongodb_ss_network_numRequests{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "requests"), target(f'rate(mongodb_ss_network_ingressRequestRateLimiter_attemptedAdmissions{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "attempted"), target(f'rate(mongodb_ss_network_ingressRequestRateLimiter_successfulAdmissions{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "successful"), target(f'rate(mongodb_ss_network_ingressRequestRateLimiter_exemptedAdmissions{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "exempted"), target(f'rate(mongodb_ss_network_ingressRequestRateLimiter_rejectedAdmissions{{instance="$instance"}}[{RATE_INTERVAL}])', 4, "rejected")], "unit": "ops", "metrics": ["mongodb_ss_network_numRequests", "mongodb_ss_network_ingressRequestRateLimiter_attemptedAdmissions", "mongodb_ss_network_ingressRequestRateLimiter_successfulAdmissions", "mongodb_ss_network_ingressRequestRateLimiter_exemptedAdmissions", "mongodb_ss_network_ingressRequestRateLimiter_rejectedAdmissions"]},
            {"title": "Cursors Open - Current Values", "description": "Currently open cursors by cursor subtype. Rising no-timeout or pinned cursors can indicate application-side cursor leaks.", "targets": [target('mongodb_ss_metrics_cursor_open{instance="$instance"}', 0, "{{csr_type}}")], "unit": "short", "metrics": ["mongodb_ss_metrics_cursor_open"]},
            {"title": "Cursor Lifecycle - Count/sec", "description": "Rate of cursor opens and cursor timeouts. Sudden timeout spikes often correlate with slow consumers or abandoned cursors.", "targets": [target(f'rate(mongodb_ss_metrics_cursor_totalOpened{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "opened"), target(f'rate(mongodb_ss_metrics_cursor_timedOut{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "timed out")], "unit": "ops", "metrics": ["mongodb_ss_metrics_cursor_totalOpened", "mongodb_ss_metrics_cursor_timedOut"]},
        ]),
        ("Memory & Cache", [
            {"title": "Memory Footprint - Bytes", "description": "Resident memory from serverStatus plus key WiredTiger allocation gauges. Helps separate process growth from cache growth.", "targets": [target('max(mongodb_ss_mem_resident{instance="$instance"}) * 1024 * 1024', 0, "resident"), target('mongodb_ss_wt_cache_bytes_currently_in_the_cache{instance="$instance"}', 1, "wt cache"), target('mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{instance="$instance"}', 2, "dirty cache")], "unit": "bytes", "metrics": ["mongodb_ss_mem_resident", "mongodb_ss_wt_cache_bytes_currently_in_the_cache", "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache"]},
            {"title": "WT Cache Capacity - Bytes", "description": "WiredTiger cache current bytes, configured maximum, and dirty bytes. Use this to judge whether memory pressure is driven by cache occupancy or dirty-page buildup.", "targets": [target('mongodb_ss_wt_cache_bytes_currently_in_the_cache{instance="$instance"}', 0, "current"), target('mongodb_ss_wt_cache_maximum_bytes_configured{instance="$instance"}', 1, "max configured"), target('mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache{instance="$instance"}', 2, "dirty")], "unit": "bytes", "metrics": ["mongodb_ss_wt_cache_bytes_currently_in_the_cache", "mongodb_ss_wt_cache_maximum_bytes_configured", "mongodb_ss_wt_cache_tracked_dirty_bytes_in_the_cache"]},
            {"title": "WT Cache IO - Bytes/sec", "description": "Rate of bytes read into and written from the WiredTiger cache. Large imbalances can hint at read bursts or eviction/checkpoint pressure.", "targets": [target(f'rate(mongodb_ss_wt_cache_bytes_read_into_cache{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "read into cache"), target(f'rate(mongodb_ss_wt_cache_bytes_written_from_cache{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "written from cache")], "unit": "Bps", "metrics": ["mongodb_ss_wt_cache_bytes_read_into_cache", "mongodb_ss_wt_cache_bytes_written_from_cache"]},
            {"title": "WT Eviction Pressure - Count/sec", "description": "Eviction trigger reaches, space wait timeouts, and failed eviction attempts. This is a high-signal panel when cache pressure becomes user-visible.", "targets": [target(f'rate(mongodb_ss_wt_cache_number_of_times_eviction_trigger_was_reached{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "eviction trigger"), target(f'rate(mongodb_ss_wt_cache_number_of_times_dirty_trigger_was_reached{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "dirty trigger"), target(f'rate(mongodb_ss_wt_cache_operations_timed_out_waiting_for_space_in_cache{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "space timeout"), target(f'rate(mongodb_ss_wt_cache_pages_selected_for_eviction_unable_to_be_evicted{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "unable to evict")], "unit": "ops", "metrics": ["mongodb_ss_wt_cache_number_of_times_eviction_trigger_was_reached", "mongodb_ss_wt_cache_number_of_times_dirty_trigger_was_reached", "mongodb_ss_wt_cache_operations_timed_out_waiting_for_space_in_cache", "mongodb_ss_wt_cache_pages_selected_for_eviction_unable_to_be_evicted"]},
        ]),
        ("Locks & Flow Control", [
            {"title": "Global Lock Queue - Current Values", "description": "Readers, writers, and total operations currently queued on the global lock. Non-zero sustained queues usually merit deeper lock analysis.", "targets": [target('mongodb_ss_globalLock_currentQueue{instance="$instance"}', 0, "{{count_type}}")], "unit": "short", "metrics": ["mongodb_ss_globalLock_currentQueue"]},
            {"title": "Active Clients - Current Values", "description": "Current active readers, writers, and total clients according to serverStatus.globalLock.activeClients.", "targets": [target('mongodb_ss_globalLock_activeClients_readers{instance="$instance"}', 0, "readers"), target('mongodb_ss_globalLock_activeClients_writers{instance="$instance"}', 1, "writers"), target('mongodb_ss_globalLock_activeClients_total{instance="$instance"}', 2, "total")], "unit": "short", "metrics": ["mongodb_ss_globalLock_activeClients_readers", "mongodb_ss_globalLock_activeClients_writers", "mongodb_ss_globalLock_activeClients_total"]},
            {"title": "Lock Acquire Rate - Count/sec", "description": "Global and collection lock acquisition rates by resource and lock mode. Useful when debugging contention spikes.", "targets": [target(f'sum by (resource, lock_mode) (rate(mongodb_ss_locks_acquireCount{{instance="$instance",resource=~"Global|Collection|Database|ReplicationStateTransition"}}[{RATE_INTERVAL}]))', 0, "{{resource}} {{lock_mode}}")], "unit": "ops", "metrics": ["mongodb_ss_locks_acquireCount"]},
            {"title": "Flow Control State - Current Values", "description": "Shows whether flow control is enabled or lagged, along with the current locks-per-kilo-op and rate limits.", "targets": [target('mongodb_ss_flowControl_enabled{instance="$instance"}', 0, "enabled"), target('mongodb_ss_flowControl_isLagged{instance="$instance"}', 1, "lagged"), target('mongodb_ss_flowControl_locksPerKiloOp{instance="$instance"}', 2, "locks/KOp"), target('mongodb_ss_flowControl_sustainerRate{instance="$instance"}', 3, "sustainer rate"), target('mongodb_ss_flowControl_targetRateLimit{instance="$instance"}', 4, "target rate")], "unit": "none", "metrics": ["mongodb_ss_flowControl_enabled", "mongodb_ss_flowControl_isLagged", "mongodb_ss_flowControl_locksPerKiloOp", "mongodb_ss_flowControl_sustainerRate", "mongodb_ss_flowControl_targetRateLimit"]},
            {"title": "Flow Control Delay - Microseconds/sec", "description": "Per-second rate of time spent lagged or acquiring tickets due to flow control. Sustained growth here often maps to replica lag pressure.", "targets": [target(f'rate(mongodb_ss_flowControl_isLaggedTimeMicros{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "lagged time"), target(f'rate(mongodb_ss_flowControl_timeAcquiringMicros{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "acquiring time")], "unit": "µs", "metrics": ["mongodb_ss_flowControl_isLaggedTimeMicros", "mongodb_ss_flowControl_timeAcquiringMicros"]},
        ]),
        ("Transactions & Errors", [
            {"title": "Transactions - Current Values", "description": "Current open, active, inactive, and prepared transactions. Rising open or prepared counts can block oplog visibility and consume cache.", "targets": [target('mongodb_ss_transactions_currentOpen{instance="$instance"}', 0, "open"), target('mongodb_ss_transactions_currentActive{instance="$instance"}', 1, "active"), target('mongodb_ss_transactions_currentInactive{instance="$instance"}', 2, "inactive"), target('mongodb_ss_transactions_currentPrepared{instance="$instance"}', 3, "prepared")], "unit": "short", "metrics": ["mongodb_ss_transactions_currentOpen", "mongodb_ss_transactions_currentActive", "mongodb_ss_transactions_currentInactive", "mongodb_ss_transactions_currentPrepared"]},
            {"title": "Transactions Lifecycle - Count/sec", "description": "Per-second transaction starts, commits, aborts, and prepares. Helpful for spotting sudden abort storms or changing transaction mix.", "targets": [target(f'rate(mongodb_ss_transactions_totalStarted{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "started"), target(f'rate(mongodb_ss_transactions_totalCommitted{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "committed"), target(f'rate(mongodb_ss_transactions_totalAborted{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "aborted"), target(f'rate(mongodb_ss_transactions_totalPrepared{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "prepared")], "unit": "ops", "metrics": ["mongodb_ss_transactions_totalStarted", "mongodb_ss_transactions_totalCommitted", "mongodb_ss_transactions_totalAborted", "mongodb_ss_transactions_totalPrepared"]},
            {"title": "Operation Issues - Count/sec", "description": "High-signal error and contention counters, including write conflicts, prepare conflicts, scan-and-order, network timeouts, and client disconnect kills.", "targets": [target(f'rate(mongodb_ss_metrics_operation_writeConflicts{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "write conflicts"), target(f'rate(mongodb_ss_metrics_operation_prepareConflicts{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "prepare conflicts"), target(f'rate(mongodb_ss_metrics_operation_scanAndOrder{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "scan & order"), target(f'rate(mongodb_ss_metrics_operation_numConnectionNetworkTimeouts{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "network timeouts"), target(f'rate(mongodb_ss_metrics_operation_killedDueToClientDisconnect{{instance="$instance"}}[{RATE_INTERVAL}])', 4, "killed on disconnect"), target(f'rate(mongodb_ss_metrics_operation_temporarilyUnavailableErrors{{instance="$instance"}}[{RATE_INTERVAL}])', 5, "temporarily unavailable")], "unit": "ops", "metrics": ["mongodb_ss_metrics_operation_writeConflicts", "mongodb_ss_metrics_operation_prepareConflicts", "mongodb_ss_metrics_operation_scanAndOrder", "mongodb_ss_metrics_operation_numConnectionNetworkTimeouts", "mongodb_ss_metrics_operation_killedDueToClientDisconnect", "mongodb_ss_metrics_operation_temporarilyUnavailableErrors"]},
            {"title": "Asserts - Count/sec", "description": "MongoDB assert rates by assert type. Any sustained non-user assert activity typically deserves investigation.", "targets": [target(f'sum by (assert_type) (rate(mongodb_ss_asserts{{instance="$instance"}}[{RATE_INTERVAL}]))', 0, "{{assert_type}}")], "unit": "ops", "metrics": ["mongodb_ss_asserts"]},
        ]),
        ("Replication & HA", [
            {"title": "Replication Apply & Network - Ops/sec", "description": "Replication apply and network operation rates. Useful when troubleshooting lag, catch-up speed, or replication stalls.", "targets": [target(f'rate(mongodb_ss_metrics_repl_apply_ops{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "apply ops"), target(f'rate(mongodb_ss_metrics_repl_network_ops{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "network ops"), target(f'rate(mongodb_ss_metrics_repl_syncSource_numSelections{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "sync source selections")], "unit": "ops", "metrics": ["mongodb_ss_metrics_repl_apply_ops", "mongodb_ss_metrics_repl_network_ops", "mongodb_ss_metrics_repl_syncSource_numSelections"]},
            {"title": "Replication Batch Time - Milliseconds/sec", "description": "Per-second accumulation of replication batch and getMore processing time. Rising values indicate replication work is consuming more time each second.", "targets": [target(f'rate(mongodb_ss_metrics_repl_apply_batches_totalMillis{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "apply batches"), target(f'rate(mongodb_ss_metrics_repl_write_batches_totalMillis{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "write batches"), target(f'rate(mongodb_ss_metrics_repl_network_getmores_totalMillis{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "network getMores"), target(f'rate(mongodb_ss_metrics_repl_network_oplogGetMoresProcessed_totalMillis{{instance="$instance"}}[{RATE_INTERVAL}])', 3, "oplog getMores")], "unit": "ms", "metrics": ["mongodb_ss_metrics_repl_apply_batches_totalMillis", "mongodb_ss_metrics_repl_write_batches_totalMillis", "mongodb_ss_metrics_repl_network_getmores_totalMillis", "mongodb_ss_metrics_repl_network_oplogGetMoresProcessed_totalMillis"]},
            {"title": "Replication Queues & Waiters - Current Values", "description": "Current replication queue sizes and waiters. Useful when diagnosing heartbeat backlog or replication coordinator waits.", "targets": [target('mongodb_ss_metrics_repl_heartBeat_handleQueueSize{instance="$instance"}', 0, "heartbeat queue"), target('mongodb_ss_metrics_repl_executor_queues_networkInProgress{instance="$instance"}', 1, "network in progress"), target('mongodb_ss_metrics_repl_waiters_replication{instance="$instance"}', 2, "replication waiters")], "unit": "short", "metrics": ["mongodb_ss_metrics_repl_heartBeat_handleQueueSize", "mongodb_ss_metrics_repl_executor_queues_networkInProgress", "mongodb_ss_metrics_repl_waiters_replication"]},
            {"title": "Replication Exceptions - Count/sec", "description": "Sync source changes, initial sync failures, and state-transition kills. These counters are useful when replica-set topology or recovery behavior is unstable.", "targets": [target(f'rate(mongodb_ss_metrics_repl_syncSource_numSyncSourceChangesDueToSignificantlyCloserNode{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "sync source changed"), target(f'rate(mongodb_ss_metrics_repl_initialSync_failedAttempts{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "initial sync failed"), target(f'rate(mongodb_ss_metrics_repl_stateTransition_totalOperationsKilled{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "state transition killed")], "unit": "ops", "metrics": ["mongodb_ss_metrics_repl_syncSource_numSyncSourceChangesDueToSignificantlyCloserNode", "mongodb_ss_metrics_repl_initialSync_failedAttempts", "mongodb_ss_metrics_repl_stateTransition_totalOperationsKilled"]},
        ]),
        ("System Pressure", [
            {"title": "Host Memory - Bytes", "description": "Host free, available, and swap-free memory converted from kilobytes to bytes. Useful when MongoDB pressure is actually OS memory pressure.", "targets": [target('mongodb_sys_memory_MemAvailable_kb{instance="$instance"} * 1024', 0, "mem available"), target('mongodb_sys_memory_MemFree_kb{instance="$instance"} * 1024', 1, "mem free"), target('mongodb_sys_memory_SwapFree_kb{instance="$instance"} * 1024', 2, "swap free")], "unit": "bytes", "metrics": ["mongodb_sys_memory_MemAvailable_kb", "mongodb_sys_memory_MemFree_kb", "mongodb_sys_memory_SwapFree_kb"]},
            {"title": "Pressure Stall Time - Microseconds/sec", "description": "Per-second CPU, IO, and memory pressure stall time. Rising IO pressure often aligns with storage bottlenecks or checkpoint pressure.", "targets": [target(f'rate(mongodb_ss_extra_info_pressure_cpu_some_totalMicros{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "cpu some"), target(f'rate(mongodb_ss_extra_info_pressure_io_some_totalMicros{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "io some"), target(f'rate(mongodb_ss_extra_info_pressure_memory_some_totalMicros{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "memory some")], "unit": "µs", "metrics": ["mongodb_ss_extra_info_pressure_cpu_some_totalMicros", "mongodb_ss_extra_info_pressure_io_some_totalMicros", "mongodb_ss_extra_info_pressure_memory_some_totalMicros"]},
            {"title": "Page Faults & Context Switches - Count/sec", "description": "OS-level page-fault and context-switch rates reported through serverStatus.extra_info. Useful for host-side contention or memory-churn diagnosis.", "targets": [target(f'rate(mongodb_ss_extra_info_page_faults{{instance="$instance"}}[{RATE_INTERVAL}])', 0, "page faults"), target(f'rate(mongodb_ss_extra_info_voluntary_context_switches{{instance="$instance"}}[{RATE_INTERVAL}])', 1, "voluntary cs"), target(f'rate(mongodb_ss_extra_info_involuntary_context_switches{{instance="$instance"}}[{RATE_INTERVAL}])', 2, "involuntary cs")], "unit": "ops", "metrics": ["mongodb_ss_extra_info_page_faults", "mongodb_ss_extra_info_voluntary_context_switches", "mongodb_ss_extra_info_involuntary_context_switches"]},
        ]),
    ]
    for row_title, specs in rows:
        panel_id, y, records = add_row(panels, panel_id, y, row_title, specs)
        row_records.append({"title": row_title, "panels": records})
    dashboard = {"__inputs": [{"name": "DS_PROMETHEUS", "label": "Prometheus", "description": "", "type": "datasource", "pluginId": "prometheus", "pluginName": "Prometheus"}], "annotations": {"list": [{"builtIn": 1, "datasource": {"type": "grafana", "uid": "-- Grafana --"}, "enable": True, "hide": True, "iconColor": "rgba(0, 211, 255, 1)", "name": "Annotations & Alerts", "type": "dashboard"}]}, "description": "Focused troubleshooting dashboard generated from curated MongoDB exporter metrics. Uses a single instance selector, row-based layout, type-aware PromQL, and per-panel descriptions.", "editable": True, "graphTooltip": 0, "links": [], "panels": panels, "refresh": "30s", "schemaVersion": 39, "style": "dark", "tags": ["mongodb", "mongodb_exporter", "core-metrics", "troubleshooting"], "templating": {"list": [{"current": {"selected": False, "text": "", "value": ""}, "datasource": PROM_DS, "definition": "label_values(mongodb_up, instance)", "hide": 0, "includeAll": False, "label": "Instance", "multi": False, "name": "instance", "options": [], "query": {"query": "label_values(mongodb_up, instance)", "refId": "PrometheusVariableQueryEditor-VariableQuery"}, "refresh": 1, "regex": "", "skipUrlSync": False, "sort": 1, "type": "query"}]}, "time": {"from": "now-6h", "to": "now"}, "timezone": "", "title": "MongoDB Exporter - Core Metrics", "uid": "mongodb-exporter-core-metrics", "version": 1, "weekStart": ""}
    progress = {"generated_at": datetime.now(UTC).isoformat(), "dashboard": str(OUTPUT), "panel_count": len([panel for panel in panels if panel.get("type") != "row"]), "rows": row_records, "selection_principle": "Focused troubleshooting metrics only; excludes long-tail/exporter-complete coverage from the all-metrics dashboard.", "notes": {"instance_variable": "Single-select instance variable with includeAll disabled.", "query_strategy": "Curated panels mix gauges and rate() queries only when the metric semantics match the intended troubleshooting view.", "source_of_truth": "Metric names and types come from Monitoring/mongodb_exporter_result.txt and the corrected inferred type pass."}}
    return dashboard, progress


if __name__ == "__main__":
    dashboard, progress = build_dashboard()
    PROGRESS.write_text(json.dumps(progress, indent=2) + "\n")
    OUTPUT.write_text(json.dumps(dashboard, indent=2) + "\n")
    print(f"Wrote {PROGRESS}")
    print(f"Wrote {OUTPUT}")