{
 "title": "MongoDB Exporter - All Metrics Explorer",
 "tags": [
  "mongodb",
  "mongodb_exporter",
  "all-metrics"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(mongodb_up, instance)"
    }
   },
   {
    "name": "metric_regex",
    "label": "Metric regex",
    "query": "mongodb_.*|go_.*|process_.*|collector_.*"
   }
  ]
 },
 "panels": [
  { "title": "Metric Explorer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Custom Metric Regex Explorer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "{__name__=~\"$metric_regex\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "MongoDB Core", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Dbstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_dbstats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Fcv",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_fcv($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pbm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_pbm($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_profile($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_status($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Transportlayerstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_transportLayerStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "MongoDB Top", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Top Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_commands($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Getmore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_getmore($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Insert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_insert($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_queries($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Readlock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_readLock($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Remove",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_remove($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_total($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Update",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_update($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Top Writelock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_top_writeLock($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Serverstatus Asserts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_asserts($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Batcheddeletes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_batchedDeletes($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Catalogstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_catalogStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Changestreampreimages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_changeStreamPreImages($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Collectioncatalog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_collectionCatalog($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_connections($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Electionmetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_electionMetrics($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus End",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 103 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_end($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Extra",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_extra($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Featurecompatibilityversion",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_featureCompatibilityVersion($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Fle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 119 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_fle($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Flowcontrol",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 119 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_flowControl($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Ftdccollectionmetrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 127 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_ftdcCollectionMetrics($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Globallock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 127 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_globalLock($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Incrementalrollout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 135 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_incrementalRollout($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Indexbuilds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 135 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_indexBuilds($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Indexbulkbuilder",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_indexBulkBuilder($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Indexstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_indexStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Intentregistry",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 151 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_intentRegistry($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Internaltransactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 151 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_internalTransactions($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Localtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_localTime($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Locks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_locks($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Logicalsessionrecordcache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_logicalSessionRecordCache($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_mem($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Abortexpiredtransactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_abortExpiredTransactions($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Abortoldesttransactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_abortOldestTransactions($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Aggstagecounters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_aggStageCounters($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Cachepressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_cachePressure($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Changestreams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 191 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_changeStreams($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Commands",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 191 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_commands($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Cursor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 199 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_cursor($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Diskspacemonitor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 199 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_diskSpaceMonitor($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Document",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 207 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_document($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Dotsanddollarsfields",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 207 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_dotsAndDollarsFields($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Getlasterror",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_getLastError($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Logging",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_logging($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Mongos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_mongos($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 223 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_network($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_operation($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Operatorcounters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 231 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_operatorCounters($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Oplogstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_oplogStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 239 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_query($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Queryexecutor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 247 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_queryExecutor($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Querystats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 247 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_queryStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Repl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 255 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_repl($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Storage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 255 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_storage($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Timeseries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 263 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_timeseries($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Metrics Ttl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 263 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_metrics_ttl($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Mirroredreads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 271 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_mirroredReads($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 271 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_network($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Ok",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 279 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_ok($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Oplatencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 279 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_opLatencies($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Opworkingtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 287 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_opWorkingTime($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Opcounters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 287 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_opcounters($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Opcountersrepl",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 295 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_opcountersRepl($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Oplogtruncation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 295 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_oplogTruncation($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Pid",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 303 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_pid($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Profiler",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 303 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_profiler($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Querysettings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 311 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_querySettings($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Queues",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 311 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_queues($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Readconcerncounters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 319 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_readConcernCounters($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Recoveryoplogapplier",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 319 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_recoveryOplogApplier($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Scramcache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 327 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_scramCache($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Security",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 327 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_security($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Spillwiredtiger",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 335 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_spillWiredTiger($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 335 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_start($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Storageengine",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 343 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_storageEngine($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Tcmalloc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 343 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_tcmalloc($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Trafficrecording",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 351 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_trafficRecording($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Transactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 351 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_transactions($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Transportsecurity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 359 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_transportSecurity($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Twophasecommitcoordinator",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 359 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_twoPhaseCommitCoordinator($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Uptime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 367 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_uptime($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Uptimeestimate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 367 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_uptimeEstimate($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Uptimemillis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 375 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_uptimeMillis($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Autocommit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 375 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_autocommit($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Background",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 383 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_background($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Backup",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 383 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_backup($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 391 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_block($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Cache",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 391 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_cache($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 399 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_capacity($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Checkpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 399 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_checkpoint($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Chunk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 407 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_chunk($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Concurrenttransactions",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 407 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_concurrentTransactions($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 415 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_connection($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Connectionstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 415 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_connectionStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Cursor",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 423 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_cursor($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 423 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_data($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Historystoragestats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 431 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_historyStorageStats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Live",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 431 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_live($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Lock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 439 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_lock($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Log",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 439 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_log($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Oplog",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 447 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_oplog($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Perf",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 447 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_perf($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Prefetch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 455 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_prefetch($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Reconciliation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 455 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_reconciliation($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Session",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 463 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_session($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Snapshot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 463 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_snapshot($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 471 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_thread($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Serverstatus Wt Txn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 471 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_ss_wt_txn($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "System Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 480 } },
  {
   "title": "System Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 481 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_cpu($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Disks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 481 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_disks($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System End",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 489 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_end($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 489 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_files($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 497 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_memory($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 497 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_available($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Boot",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 505 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_boot($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 505 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_capacity($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Dev",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 513 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_dev($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Free",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 513 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_free($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Run",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 521 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_run($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Mounts Snap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 521 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_mounts_snap($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Netstat Ip",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 529 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_netstat_Ip($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Netstat Ipext",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 529 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_netstat_IpExt($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Netstat Tcp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 537 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_netstat_Tcp($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Netstat Tcpext",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 537 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_netstat_TcpExt($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Pressure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 545 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_pressure($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Sockstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 545 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_sockstat($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 553 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_start($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 553 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_status($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "System Vmstat",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 561 },
   "targets": [
    {
     "expr": "{__name__=~\"mongodb_sys_vmstat($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 570 } },
  {
   "title": "Collector",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 571 },
   "targets": [
    {
     "expr": "{__name__=~\"collector($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Gc",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 571 },
   "targets": [
    {
     "expr": "{__name__=~\"go_gc($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 579 },
   "targets": [
    {
     "expr": "{__name__=~\"go_goroutines($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Info",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 579 },
   "targets": [
    {
     "expr": "{__name__=~\"go_info($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Memstats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 587 },
   "targets": [
    {
     "expr": "{__name__=~\"go_memstats($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Sched",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 587 },
   "targets": [
    {
     "expr": "{__name__=~\"go_sched($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Go Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 595 },
   "targets": [
    {
     "expr": "{__name__=~\"go_threads($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 595 },
   "targets": [
    {
     "expr": "{__name__=~\"process($|_.*)\",instance=~\"$instance\"}"
    }
   ]
  }
 ]
}